import { expect, test } from '@playwright/test'
import { DEMO_TITLE, assertNoErrors, collectErrors, openApp } from './helpers'

test('share link → import in a new context → same title', async ({ page, browser }) => {
  const log = collectErrors(page)
  const id = await openApp(page)
  await page.goto(`/#/set/${id}`)
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByText('Share this set')).toBeVisible()
  const link = await dialog.getByRole('textbox', { name: 'Share link' }).inputValue()
  expect(link).toContain('#/import?d=1.')
  await expect(dialog.getByRole('img', { name: /QR code/ })).toBeVisible()
  assertNoErrors(log)

  const ctx = await browser.newContext()
  const page2 = await ctx.newPage()
  const log2 = collectErrors(page2)
  await page2.goto(link)
  const skip = page2.getByRole('button', { name: /^Skip$/ })
  if (await skip.isVisible({ timeout: 1500 }).catch(() => false)) await skip.click()
  await expect(page2.getByRole('heading', { name: 'Import set' })).toBeVisible()
  await expect(page2.getByText('Preview')).toBeVisible()
  await expect(page2.getByText('Active recall').first()).toBeVisible()
  await page2.getByRole('button', { name: /^(Import|Import as copy)$/ }).first().click()
  await page2.waitForURL(/#\/set\/[^/]+$/)
  await expect(page2.getByRole('heading', { level: 1, name: DEMO_TITLE })).toBeVisible()
  await expect(page2.getByText('12 terms')).toBeVisible()
  assertNoErrors(log2)
  await ctx.close()
})

test('export JSON → import the file via /#/import', async ({ page }) => {
  const log = collectErrors(page)
  const id = await openApp(page)
  await page.goto(`/#/set/${id}`)
  await page.getByRole('button', { name: 'More actions' }).click()
  await page.getByRole('menuitem', { name: 'Export' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByText('Export set')).toBeVisible()
  const [download] = await Promise.all([page.waitForEvent('download'), dialog.getByRole('button', { name: 'Download' }).click()])
  expect(download.suggestedFilename()).toMatch(/\.json$/)
  const path = await download.path()
  expect(path).toBeTruthy()

  await page.goto('/#/import')
  await expect(page.getByRole('heading', { name: 'Import set' })).toBeVisible()
  const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: 'Choose file' }).click()])
  await chooser.setFiles(path!)
  await expect(page.getByText('Preview')).toBeVisible()
  await page.getByRole('button', { name: /^(Import|Import as copy)$/ }).first().click()
  await page.waitForURL(/#\/set\/[^/]+$/)
  const newId = /#\/set\/([^/?]+)/.exec(page.url())![1]
  expect(newId).not.toBe(id)
  await expect(page.getByRole('heading', { level: 1, name: DEMO_TITLE })).toBeVisible()
  await expect(page.getByText('12 terms')).toBeVisible()
  assertNoErrors(log)
})
